### ISSUE TITLE
Not working with current setup

### ISSUE THREAD

**Issue by MImranAsghar** [europeana/media-player#88]
Hi,
I have been trying to run the media player using npm module - europeanamediaplayer. However, it keeps giving me error even though I am following the steps of adding jQuery and creating videoObj. Can you please let me know whether something has changed and your readme is maybe outdated? This is my try: https://codesandbox.io/s/javascript-wx239?file=/index.html

**Comment by MImranAsghar** [comment]
@blokjonathan

**Comment by pietervanleeuwen** [comment]
Hi,

The README in the develop branch (main branch configured for this repo) should be up to date. From there I created this minimal jsfiddle to show how to get a working example of the Europeana Media player.

https://jsfiddle.net/7dqeh5rc/
